import { Eye, ImageOff } from "lucide-react";

export default function GradCamView({ imageUrl }) {
  return (
    <div className="bg-card border border-border rounded-2xl p-5">
      <div className="flex items-center gap-2 mb-3">
        <Eye className="w-4 h-4 text-blue-500" />
        <span className="font-semibold text-sm text-foreground">Grad-CAM Heatmap (ViT XAI)</span>
      </div>
      <p className="text-xs text-muted-foreground mb-4">
        Highlights regions the Vision Transformer focused on when classifying. Red = high attention, blue = low.
      </p>
      {imageUrl ? (
        <img
          src={imageUrl}
          alt="Grad-CAM heatmap overlay"
          className="w-full rounded-xl object-cover"
          onError={(e) => { e.target.style.display = "none"; }}
        />
      ) : (
        <div className="h-40 bg-muted rounded-xl flex flex-col items-center justify-center gap-2">
          <ImageOff className="w-8 h-8 text-muted-foreground" />
          <p className="text-xs text-muted-foreground">Grad-CAM generated by backend</p>
          <p className="text-xs text-muted-foreground">Run the Python API to see this output</p>
        </div>
      )}
    </div>
  );
}