import { Music2, ImageOff } from "lucide-react";

export default function SpectrogramView({ imageUrl }) {
  return (
    <div className="bg-card border border-border rounded-2xl p-5">
      <div className="flex items-center gap-2 mb-3">
        <Music2 className="w-4 h-4 text-purple-500" />
        <span className="font-semibold text-sm text-foreground">Mel Spectrogram (Wav2Vec2 XAI)</span>
      </div>
      <p className="text-xs text-muted-foreground mb-4">
        Audio frequency content over time. Synthetic voices show unnatural spectral patterns and vocoder artifacts.
      </p>
      {imageUrl ? (
        <img
          src={imageUrl}
          alt="Mel Spectrogram"
          className="w-full rounded-xl object-cover"
          onError={(e) => { e.currentTarget.style.display = "none"; }}
        />
      ) : (
        <div className="h-40 bg-muted rounded-xl flex flex-col items-center justify-center gap-2">
          <ImageOff className="w-8 h-8 text-muted-foreground" />
          <p className="text-xs text-muted-foreground">Spectrogram generated by backend</p>
          <p className="text-xs text-muted-foreground">Run the Python API to see this output</p>
        </div>
      )}
    </div>
  );
}